title: Welcome to my Blog
author: Cherian Paul
email:  no@email.com
description: > # this means to ignore newlines until "baseurl:"
  I believe in Free and Open Source software for everyone. The world will become a better place 
  if we all contribute freely and collectively. 

# social links
twitter_username: cherianmpaul
github_username:  cherianmpaul

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
